name: check-deployment

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/check-deployment.yaml"
      - "tools/**"
      - "weatherman/**"
  workflow_dispatch:

jobs:
  check-deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Wait for deployment and check site health
      uses: nick-fields/retry@v3
      with:
        timeout_seconds: 30
        max_attempts: 10
        retry_wait_seconds: 15
        command: |
          chmod +x ./scripts/test_deployment.sh
          ./scripts/test_deployment.sh
