name: pytest

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/pytest.yaml"
      - "tests/**"
      - "tools/**"
      - "weatherman/**"

  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run all tests
        run: |
          pip install pytest
          pytest tests -v
